# -*- coding: utf-8 -*-
import os
import subprocess
import yaml
import glob


CLABVERTER_BIN = "/usr/local/bin/clabverter"

if not os.path.exists(CLABVERTER_BIN) or not os.access(CLABVERTER_BIN, os.X_OK):
    raise ValueError("Missing executable 'clabverter'. Please install it from https://github.com/srl-labs/clabernetes/releases/latest")


class C9sController:
    """Controller to manage ContainerLab"""

    def __init__(self):
        pass

    def parse_clab_topology(self, topology_dir):
        """Parse ContainerLab Topology Before running clabverter. We expect to have a file named '*.clab.y*ml'"""
        clab_files = glob.glob(f"{topology_dir}/*.clab.y*ml")
        if len(clab_files) != 1:
            msg = "No ContainerLab topology file!" if not clab_files else "Too many ContainerLab topology files!"
            return False, msg + " You must provide one file named *.clab.yaml"
        try:
            with open(clab_files[0], 'r') as f:
                topology = yaml.safe_load(f)
        except Exception as exc:
            return False, f"Failed to load ContainerLab topolgy: {exc}"
        return True, topology

    def convert_clab(self, topology_dir, clab_uuid=None, destination_namespace=None):
        """Convert the container lab topology into a kubernetes manifest."""
        try:
            result = subprocess.run(
                [CLABVERTER_BIN, "--stdout", "--quiet"],
                cwd=topology_dir,
                capture_output=True,
                text=True,
                check=True
            )
        except subprocess.CalledProcessError as exc:
            return False, f"Convert ContainerLab failed: {exc} -- {exc.stderr}"
        except Exception as exc:
            return False, f"Convert ContainerLab failed: {exc}"
        docs = result.stdout.split("---\n")
        clab_name = ""
        for idx, doc in enumerate(docs):
            yaml_doc = yaml.safe_load(doc)
            if not yaml_doc:
                continue
            if yaml_doc.get("kind") == "Namespace":
                clab_name = yaml_doc.get("metadata", {}).get("name", "").removeprefix("c9s-")
                break
        else:
            return False, "Convert ContainerLab failed: could not find Namespace component"

        # XXX: we will force namespace to be the configured one, so we remove the namespace generated by clabverter
        del docs[idx]

        for i in range(len(docs)):
            docs[i] = docs[i].replace(f"ame: {clab_name}", f"ame: clab-{clab_uuid}")
            if destination_namespace:
                docs[i] = docs[i].replace(
                    f": c9s-{clab_name}\n", f": {destination_namespace}\n"
                )

        return True, "---\n".join(docs)

