"""Add commment and grade  properties to LabAnswers

Revision ID: 2.0.3
Revises: 2.0.2
Create Date: 2025-08-18 17:32:46.121707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2.0.3'
down_revision = '2.0.2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lab_answers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comments', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('grades', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lab_answers', schema=None) as batch_op:
        batch_op.drop_column('grades')
        batch_op.drop_column('comments')

    # ### end Alembic commands ###
