"""Added lab_metadata table, added columns expiration_ts and finish_reason into lab_instances, removed labs.category_id in favor of labs_category relation

Revision ID: 2.0.5
Revises: 2.0.4
Create Date: 2026-06-23 09:32:53.708929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2.0.5'
down_revision = '2.0.4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lab_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('short_uuid', sa.String(length=14), nullable=True),
    sa.Column('is_clab', sa.Boolean(), nullable=True),
    sa.Column('_md', sa.String(), nullable=True),
    sa.Column('lab_id', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lab_id'], ['labs.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('short_uuid')
    )
    with op.batch_alter_table('lab_instances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expiration_ts', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('finish_reason', sa.String(length=255), nullable=True))

    with op.batch_alter_table('labs', schema=None) as batch_op:
        #batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('category_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('labs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key(None, 'lab_categories', ['category_id'], ['id'])

    with op.batch_alter_table('lab_instances', schema=None) as batch_op:
        batch_op.drop_column('finish_reason')
        batch_op.drop_column('expiration_ts')

    op.drop_table('lab_metadata')
    # ### end Alembic commands ###
