"""Add lab_field_versions for version control of editable Lab fields

Creates the table and backfills version 1 for every existing lab from its
current manifest, lab_guide and extended_desc, so history starts populated.

Revision ID: 2.0.11
Revises: 2.0.10
Create Date: 2026-07-05 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2.0.11'
down_revision = '2.0.10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'lab_field_versions',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('lab_id', sa.String(length=40), nullable=False),
        sa.Column('field', sa.String(length=32), nullable=False, server_default='manifest'),
        sa.Column('version', sa.Integer(), nullable=False),
        sa.Column('content', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('updated_by', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['lab_id'], ['labs.id']),
        sa.ForeignKeyConstraint(['updated_by'], ['users.id']),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('lab_id', 'field', 'version', name='uq_lab_field_version'),
    )
    # ### end Alembic commands ###

    # backfill: version 1 of each non-empty tracked field for every existing lab
    import datetime

    conn = op.get_bind()
    now = datetime.datetime.now(datetime.timezone.utc)
    rows = conn.execute(
        sa.text("SELECT id, manifest, lab_guide_md, extended_desc, updated_by FROM labs")
    ).fetchall()
    insert = sa.text(
        "INSERT INTO lab_field_versions"
        " (lab_id, field, version, content, created_at, updated_at, updated_by)"
        " VALUES (:lab_id, :field, 1, :content, :now, :now, :updated_by)"
    )
    for lab_id, manifest, lab_guide_md, extended_desc, updated_by in rows:
        for field, raw in (
            ("manifest", manifest),
            ("lab_guide", lab_guide_md),
            ("extended_desc", extended_desc),
        ):
            if not raw:
                continue
            content = raw.decode() if isinstance(raw, (bytes, bytearray)) else raw
            conn.execute(
                insert,
                {
                    "lab_id": lab_id,
                    "field": field,
                    "content": content,
                    "now": now,
                    "updated_by": updated_by,
                },
            )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lab_field_versions')
    # ### end Alembic commands ###
