"""add clab_instances core

Revision ID: 2.0.5
Revises: 2.0.4
Create Date: 2025-10-12 22:56:48.583230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2.0.5'
down_revision = '2.0.4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clab_instances',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('owner_user_id', sa.Integer(), nullable=False),
    sa.Column('clab_id', sa.String(length=36), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('expiration_ts', sa.DateTime(), nullable=True),
    sa.Column('finish_reason', sa.String(length=64), nullable=True),
    sa.Column('_clab_resources', sa.Text(), nullable=True),
    sa.Column('namespace_effective', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['clab_id'], ['clabs.id'], ),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clab_instances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clab_instances_clab_id'), ['clab_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_clab_instances_expiration_ts'), ['expiration_ts'], unique=False)
        batch_op.create_index(batch_op.f('ix_clab_instances_owner_user_id'), ['owner_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_clab_instances_token'), ['token'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clab_instances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clab_instances_token'))
        batch_op.drop_index(batch_op.f('ix_clab_instances_owner_user_id'))
        batch_op.drop_index(batch_op.f('ix_clab_instances_expiration_ts'))
        batch_op.drop_index(batch_op.f('ix_clab_instances_clab_id'))

    op.drop_table('clab_instances')
    # ### end Alembic commands ###
