"""add clabs core

Revision ID: 2.0.4
Revises: 2.0.3
Create Date: 2025-10-12 22:30:57.032807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2.0.4'
down_revision = '2.0.3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clabs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('extended_desc', sa.LargeBinary(), nullable=True),
    sa.Column('clab_guide_md', sa.Text(), nullable=True),
    sa.Column('clab_guide_html', sa.Text(), nullable=True),
    sa.Column('yaml_manifest', sa.Text(), nullable=True),
    sa.Column('namespace_default', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_table('clabs')
    # ### end Alembic commands ###

