"""Added is_deleted column to labs for soft-delete support

Revision ID: 2.0.7
Revises: 2.0.6
Create Date: 2026-07-02 17:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2.0.7'
down_revision = '2.0.6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('labs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=True, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('labs', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')
    # ### end Alembic commands ###
