"""add clab groups and categories associations

Revision ID: 2.0.6
Revises: 2.0.5
Create Date: 2025-10-12 23:26:20.674605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2.0.6'
down_revision = '2.0.5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clab_categories_association',
    sa.Column('clab_id', sa.String(length=36), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['lab_categories.id'], ),
    sa.ForeignKeyConstraint(['clab_id'], ['clabs.id'], ),
    sa.PrimaryKeyConstraint('clab_id', 'category_id')
    )
    op.create_table('clab_groups',
    sa.Column('clab_id', sa.String(length=36), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['clab_id'], ['clabs.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('clab_id', 'group_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clab_groups')
    op.drop_table('clab_categories_association')
    # ### end Alembic commands ###


