"""Add commment and grade  properties to LabAnswers

Revision ID: 44c2fedea345
Revises: 2.0.2
Create Date: 2025-08-18 17:32:46.121707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44c2fedea345'
down_revision = '2.0.2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lab_answers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comments', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('grades', sa.String(), nullable=True))

    with op.batch_alter_table('lab_instances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expiration_ts', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('finish_reason', sa.String(length=255), nullable=True))

    with op.batch_alter_table('labs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('category_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('labs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key(None, 'lab_categories', ['category_id'], ['id'])

    with op.batch_alter_table('lab_instances', schema=None) as batch_op:
        batch_op.drop_column('finish_reason')
        batch_op.drop_column('expiration_ts')

    with op.batch_alter_table('lab_answers', schema=None) as batch_op:
        batch_op.drop_column('grades')
        batch_op.drop_column('comments')

    # ### end Alembic commands ###
